In [2]:
import torch
import numpy as np

# 创建张量的不同方法
print("创建张量的不同方法：")
x = torch.tensor([1, 2, 3],dtype=torch.float32)  # 从列表创建张量
print(f"从列表创建,可指定数据类型: {x}")

y = torch.from_numpy(np.array([4, 5, 6]))  # 从NumPy数组创建张量
print(f"从NumPy数组创建: {y}")

z = torch.zeros(3, 4)  # 创建全0张量
print(f"全0张量:\n{z}")

ones = torch.ones(2, 3)  # 创建全1张量
print(f"全1张量:\n{ones}")

rand_tensor = torch.rand(2, 2)  # 创建随机张量(0-1均匀分布)
print(f"随机张量:\n{rand_tensor}")

# 创建未初始化的张量
empty_tensor = torch.empty(2, 3)
print("未初始化张量:", empty_tensor)

1. 创建张量的不同方法：
从列表创建: tensor([1, 2, 3])
从NumPy数组创建: tensor([4, 5, 6], dtype=torch.int32)
全0张量:
tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])
全1张量:
tensor([[1., 1., 1.],
        [1., 1., 1.]])
随机张量:
tensor([[0.2959, 0.0606],
        [0.3224, 0.0399]])
未初始化张量: tensor([[0., 0., 0.],
        [0., 0., 0.]])


In [3]:
# 张量的维度操作
print("张量的维度操作：")
tensor = torch.rand(2, 3)
print(f"原始张量:\n{tensor}")
print(f"转置后:\n{tensor.t()}")

tensor = torch.rand(2, 3, 4)
# 形状变换
reshaped = tensor.reshape(4, 6)
print("重塑后形状:", reshaped.shape)
print(f"视图(共享数据):\n{tensor.view(4, 6)}")
print("展平后:", tensor.flatten().shape)
print("维度扩展:", tensor.unsqueeze(0).shape)  # 在第0维添加维度
print("维度压缩:", tensor[:, 0:1, :].squeeze(1).shape)  # 压缩大小为1的维度



5. 张量的维度操作：
原始张量:
tensor([[0.8984, 0.8042, 0.7931],
        [0.2995, 0.0177, 0.1964]])
转置后:
tensor([[0.8984, 0.2995],
        [0.8042, 0.0177],
        [0.7931, 0.1964]])
重塑后形状: torch.Size([4, 6])
视图(共享数据):
tensor([[9.9753e-01, 8.4997e-01, 3.5172e-01, 6.7017e-01, 9.0693e-01, 9.6868e-01],
        [8.5565e-02, 8.1011e-01, 2.2763e-01, 3.5793e-01, 7.0218e-01, 9.8127e-01],
        [3.7074e-04, 9.5176e-01, 7.7234e-01, 4.8474e-01, 5.8474e-01, 1.8669e-01],
        [5.2942e-01, 5.9628e-01, 9.0672e-01, 5.4176e-01, 7.1012e-01, 6.6131e-01]])
展平后: torch.Size([24])
维度扩展: torch.Size([1, 2, 3, 4])
维度压缩: torch.Size([2, 4])


In [4]:

# 张量的基本属性
print("\n2. 张量的基本属性：")
tensor = torch.randn(3, 4, 5)
print(f"张量形状: {tensor.shape}")
print(f"张量维度数: {tensor.ndim}")
print(f"张量元素总数: {tensor.numel()}")
print(f"张量数据类型: {tensor.dtype}")
print(f"张量所在设备: {tensor.device}")

# 张量的索引和切片
print("\n3. 张量的索引和切片：")
tensor = torch.tensor([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(f"原始张量:\n{tensor}")
print(f"第一行: {tensor[0]}")
print(f"第一列: {tensor[:, 0]}")
print(f"子矩阵:\n{tensor[0:2, 1:3]}")

# 张量的数学运算
print("\n4. 张量的数学运算：")
a = torch.tensor([1, 2, 3], dtype=torch.float32)
b = torch.tensor([4, 5, 6], dtype=torch.float32)
print(f"a + b = {a + b}")
print(f"a - b = {a - b}")
print(f"a * b (元素级乘法) = {a * b}")
print(f"a.matmul(b) (点积) = {a.matmul(b)}")



2. 张量的基本属性：
张量形状: torch.Size([3, 4, 5])
张量维度数: 3
张量元素总数: 60
张量数据类型: torch.float32
张量所在设备: cpu

3. 张量的索引和切片：
原始张量:
tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])
第一行: tensor([1, 2, 3])
第一列: tensor([1, 4, 7])
子矩阵:
tensor([[2, 3],
        [5, 6]])

4. 张量的数学运算：
a + b = tensor([5., 7., 9.])
a - b = tensor([-3., -3., -3.])
a * b (元素级乘法) = tensor([ 4., 10., 18.])
a.matmul(b) (点积) = 32.0


In [6]:
print("\n=== 张量与常量运算 ===")
tensor_2d = torch.tensor([[1, 2, 3], [4, 5, 6]], dtype=torch.float32)
constant = 10
print("张量加常量:", tensor_2d + constant)
print("张量乘常量:", tensor_2d * constant)

tensor_3d = torch.tensor([[1, 2],
                           [3,4] ,
                           [5,6]     ], dtype=torch.float32)
print("矩阵乘法(3x2 @ 2x3):", torch.matmul(tensor_3d,tensor_2d))

# 广播机制 - 不同形状的张量运算
print("\n=== 广播机制 ===")
tensor_a = torch.tensor([[1, 2, 3], [4, 5, 6]], dtype=torch.float32)  # 形状为 (2, 3)
tensor_b = torch.tensor([[10, 20, 30]], dtype=torch.float32)         # 形状为 (1, 3)
print("张量A形状:", tensor_a.shape)
print("张量B形状:", tensor_b.shape)
print("张量相加 (广播):\n", tensor_a + tensor_b)

# 另一个广播例子
tensor_c = torch.tensor([[1], [2]], dtype=torch.float32)             # 形状为 (2, 1)
print("张量C形状:", tensor_c.shape)
print("张量A与C相乘 (广播):\n", tensor_a * tensor_c)



=== 张量与常量运算 ===
张量加常量: tensor([[11., 12., 13.],
        [14., 15., 16.]])
张量乘常量: tensor([[10., 20., 30.],
        [40., 50., 60.]])
矩阵乘法(3x2 @ 2x3): tensor([[ 9., 12., 15.],
        [19., 26., 33.],
        [29., 40., 51.]])

=== 广播机制 ===
张量A形状: torch.Size([2, 3])
张量B形状: torch.Size([1, 3])
张量相加 (广播):
 tensor([[11., 22., 33.],
        [14., 25., 36.]])
张量C形状: torch.Size([2, 1])
张量A与C相乘 (广播):
 tensor([[ 1.,  2.,  3.],
        [ 8., 10., 12.]])


In [7]:
# 张量的梯度计算（自动微分）
print("张量的梯度计算：")
x = torch.tensor([2.0], requires_grad=True)
y = x**2
y.backward()
print(f"x = {x}, y = x^2 = {y}")
print(f"dy/dx = {x.grad}")

# 张量与NumPy的互操作
print("\n8. 张量与NumPy的互操作：")
tensor = torch.ones(3)
numpy_array = tensor.numpy()
print(f"Tensor转NumPy: {numpy_array} (类型: {type(numpy_array)})")

numpy_array = np.array([1.0, 2.0, 3.0])
tensor = torch.from_numpy(numpy_array)
print(f"NumPy转Tensor: {tensor} (类型: {type(tensor)})")



7. 张量的梯度计算：
x = tensor([2.], requires_grad=True), y = x^2 = tensor([4.], grad_fn=<PowBackward0>)
dy/dx = tensor([4.])

8. 张量与NumPy的互操作：
Tensor转NumPy: [1. 1. 1.] (类型: <class 'numpy.ndarray'>)
NumPy转Tensor: tensor([1., 2., 3.], dtype=torch.float64) (类型: <class 'torch.Tensor'>)
